export const RolePermissionUpdate = [
  "UPDATE `role_permission` SET `create` = '1', `update` = '1', `read` = '1', `delete` = '1' WHERE (`roleId` = '1') and (`permissionId` = '1')",
  "UPDATE `role_permission` SET `create` = '1', `update` = '1', `read` = '1', `delete` = '1' WHERE (`roleId` = '1') and (`permissionId` = '2')",
  "UPDATE `role_permission` SET `create` = '1', `update` = '1', `read` = '1', `delete` = '1' WHERE (`roleId` = '1') and (`permissionId` = '3')",
  "UPDATE `role_permission` SET `create` = '1', `update` = '1', `read` = '1', `delete` = '1' WHERE (`roleId` = '1') and (`permissionId` = '4')",
  "UPDATE `role_permission` SET `create` = '1', `update` = '1', `read` = '1', `delete` = '1' WHERE (`roleId` = '1') and (`permissionId` = '5')",
  "UPDATE `role_permission` SET `read` = '1' WHERE (`roleId` = '2') and (`permissionId` = '1')",
  "UPDATE `role_permission` SET `create` = '1' WHERE (`roleId` = '2') and (`permissionId` = '2')",
  "UPDATE `role_permission` SET `update` = '1', `read` = '1', `delete` = '1' WHERE (`roleId` = '2') and (`permissionId` = '3')",
  "UPDATE `role_permission` SET `create` = '1', `update` = '1', `read` = '1', `delete` = '1' WHERE (`roleId` = '3') and (`permissionId` = '1')",
  "UPDATE `role_permission` SET `create` = '1', `update` = '1', `read` = '1' WHERE (`roleId` = '3') and (`permissionId` = '2')",
  "UPDATE `role_permission` SET `update` = '1', `read` = '1', `delete` = '1' WHERE (`roleId` = '3') and (`permissionId` = '3')",
  "UPDATE `role_permission` SET `create` = '1', `update` = '1', `read` = '1', `delete` = '1' WHERE (`roleId` = '1') and (`permissionId` = '6')",
  "UPDATE `role_permission` SET `create` = '1', `read` = '1' WHERE (`roleId` = '2') and (`permissionId` = '6')",
  "UPDATE `role_permission` SET `read` = '1' WHERE (`roleId` = '3') and (`permissionId` = '6')",
];
